[package]
name = "rusthinq-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rusthinq-protocol = { path = "../rusthinq-protocol" }
serde_json.workspace = true
url = "2"
rusthinq-server = { path = "../rusthinq-server" }
tokio.workspace = true

reqwest = { version = "0.12.28", default-features = false, features = ["native-tls", "json"] }
openssl = "0.10"
tokio-openssl = "0.6"
base64 = "0.22"
httpdate = "1"
serde = {version="1",features=["derive"]}

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
