[package]
name = "rusthinq-scripting"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rhai = { version = "=1.26.1", features = ["sync", "internals", "serde"] }
tokio.workspace = true
rusthinq-protocol = { path = "../rusthinq-protocol" }
serde_json.workspace = true
base64 = "0.22"
